language:
    php

php:
  - 5.6
  - 7.0
  - hhvm

env:
  - MONGO_VERSION=1.2.12 PREFER_LOWEST=""
  - MONGO_VERSION=1.3.2 PREFER_LOWEST=""
  - MONGO_VERSION=1.3.7 PREFER_LOWEST=""
  - MONGO_VERSION=1.4.5 PREFER_LOWEST=""
  - MONGO_VERSION=stable PREFER_LOWEST=""
  - MONGO_VERSION=stable PREFER_LOWEST="--prefer-lowest"

before_script:
  - yes '' | pecl -q install -f mongo-${MONGO_VERSION}
  - php --ri mongo
  - composer self-update
  - composer update --dev --no-interaction --prefer-source $PREFER_LOWEST

script:
  - phpunit -c phpunit.xml.dist --colors tests
